[build-system]
requires = ["hatchling", "hatch-vcs"]        
build-backend = "hatchling.build"             

[project]
name = "python-package"
dynamic = ["version"]                         

authors = [
  { name = "Example Author", email = "author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[tool.hatch.version]
source = "vcs"                                
